name: api_client
description: Data api client package for services.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto: ^3.0.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0
    
dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.3
  json_serializable: ^6.2.0
  mockito: ^5.2.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  generate: true    # Add this line
  assets:
    - assets/
    - assets/json/