name: marvel
description: My first Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  
  dartz: ^0.10.0-nullsafety.1
  http: ^0.13.1
  dio: ^4.0.0
  json_annotation: ^4.0.1
  crypto: ^3.0.0
  cupertino_icons: ^1.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.4  
  flutter_launcher_icons: ^0.9.0
  flutter_linkify: ^5.0.0
  webview_flutter: ^2.0.3
  cached_network_image: ^3.0.0

  core_base:
    path: packages/core_base

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.0
  json_serializable: ^4.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher.png"

# The following section is specific to Flutter.
flutter:
  generate: true    # Add this line
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/menu/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
