name: marvel
description: A Marvel app to see all characters, comics and stories from Marvel API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  api_client: 
    path: packages/api_client
  bloc: ^8.0.3
  character_repository: 
    path: packages/character_repository
  comic_repository: 
    path: packages/comic_repository
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  hydrated_bloc: ^8.1.0
  intl: ^0.17.0
  path_provider: ^2.0.11
  

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/images/menu/
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/oswald.ttf
          weight: 700
