name: secure_storage
description: Package for persisting in secure storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0
