name: authentication_repository
description: Authentication repository package for credentials.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.3

dependencies: 
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  secure_storage: 
    path: ../secure_storage

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  test: ^1.21.3
  very_good_analysis: ^4.0.0
