name: marvel_domain
description: Domain package for Marvel project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.10.0-nullsafety.1
  core_domain:
    path: ../core_domain

dev_dependencies:
  flutter_test:
    sdk: flutter