name: api_client

on: 
  push:
    paths:
      - "packages/api_client/**"
      - ".github/workflows/api_client.yaml"

  pull_request:
    paths:
      - "packages/api_client/**"
      - ".github/workflows/api_client.yaml"


jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/api_client
      flutter_channel: stable
      flutter_version: 3.0.0
